# version: 2
# updates:
# 
#   - package-ecosystem: "bundler"
#     directory: "/" # Location of package manifests
#     schedule:
#       interval: "daily"
#       time: "00:00"
#     commit-message:
#       prefix: "bundle"
#     ignore:
#       - dependency-name: "*rails*"
#     versioning-strategy: lockfile-only
#       
#   - package-ecosystem: "npm"
#     directory: "/" # Location of package manifests
#     schedule:
#       interval: "daily"
#       time: "00:00"
#     commit-message:
#       prefix: "yarn"
#     ignore:
#       - dependency-name: "*rails*"
#     versioning-strategy: lockfile-only
