inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude


require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - "spec/fixtures/files/spectra/libs.spec"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

