---
include:
- "app/*.rb"
- "config/*.rb"
- "lib/**/*.rb"
- "spec/**/*"
exclude:
- "test/**/*"
- "vendor/**/*"
- ".bundle/**/*"
reporters:
- rubocop
- require_not_found
formatter:
  rubocop:
    cops: safe
plugins:
- solargraph-rails
max_files: 5000
