services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data
  guard:
    build: .
    env_file:
      - .env
    command: bundle exec guard --no-bundler-warning --no-interactions -P livereload
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle

volumes:
  pg_data:
  redis_data:
  bundle:
