services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    networks:
      - es-net
      - default
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
      - ELASTICSEARCH_URL=http://es-container:9200
      - LOGSTASH_HOST=logstash
    depends_on:
      - db
      - redis
      - elasticsearch
      - logstash
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=changeme
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data
    networks:
      - default
  guard:
    build: .
    env_file:
      - .env
    command: bundle exec guard --no-bundler-warning --no-interactions -P livereload
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    networks:
      - default
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  logstash:
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    image: docker.elastic.co/logstash/logstash-oss:7.10.2
    networks:
      - es-net
    ports:
      - 9600:9600
    depends_on:
      - elasticsearch
    volumes:
      - ./config/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./log:/usr/src/app/log

networks:
  es-net:
    driver: bridge
  default:
    driver: bridge

volumes:
  pg_data:
  redis_data:
  bundle:
