services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  logstash:
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    image: docker.elastic.co/logstash/logstash-oss:7.10.2
    networks:
      - es-net
    ports:
      - 9600:9600
    depends_on:
      - elasticsearch
    volumes:
      - ./config/logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./log:/usr/src/app/log

networks:
  es-net:
    driver: bridge
