default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  primary:
    <<: *default
    database: ITMO_HSDB_development
    username: <%= ENV['PGUSER'] %>
    password: <%= ENV['PGPASSWORD'] %>

  rsdb:
    <<: *default
    database: ITMO_RSDB_development
    username: <%= ENV['PGUSER'] %>
    password: <%= ENV['PGPASSWORD'] %>
    migrations_paths: db/rsdb_migrate

test:
  primary:
    <<: *default
    database: ITMO_HSDB_test
    username: <%= ENV['PGUSER'] %>
    password: <%= ENV['PGPASSWORD'] %>

  rsdb:
    <<: *default
    database: ITMO_RSDB_test
    username: <%= ENV['PGUSER'] %>
    password: <%= ENV['PGPASSWORD'] %>
    migrations_paths: db/rsdb_migrate

production:
  primary:
    host: <%= ENV['PGHOST'] %>
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_HSDB_production
    url: <%= ENV['HSDB_PRODUCTION'] %>

  rsdb:
    host: <%= ENV['PGHOST'] %>
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_RSDB_producion
    url: <%= ENV['RSDB_PRODUCTION'] %>
    migrations_paths: db/rsdb_migrate
