development:
  primary:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_HSDB_development
    url: <%= ENV['HSDB_DEVELOPMENT'] %>

  primary_replica:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_HSDB_development
    url: <%= ENV['HSDB_DEVELOPMENT_REPLICA'] %>
    replica: true

  rsdb:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_RSDB_development
    url: <%= ENV['RSDB_DEVELOPMENT'] %>

  rsdb_replica:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_RSDB_development
    url: <%= ENV['RSDB_DEVELOPMENT_REPLICA'] %>
    replica: true

test:
  primary:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_HSDB_test
    url: postgres://postgres:postgres@localhost/ITMO_HSDB_test

  primary_replica:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_HSDB_test
    url: postgres://postgres:postgres@localhost/ITMO_HSDB_test
    replica: true

  rsdb:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_RSDB_TEST
    url: postgres://postgres:postgres@localhost/ITMO_RSDB_test

  rsdb_replica:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_RSDB_TEST
    url: postgres://postgres:postgres@localhost/ITMO_RSDB_test
    replica: true

production:
  primary:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_HSDB_production
    url: <%= ENV['HSDB_PRODUCTION'] %>

  primary_replica:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_HSDB_production
    url: <%= ENV['HSDB_PRODUCTION_REPLICA'] %>
    replica: true

  rsdb:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_RSDB_producion
    url: <%= ENV['RSDB_PRODUCTION'] %>

  secondary_replica:
    host: localhost
    adapter: postgresql
    encoding: utf8
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: ITMO_RSDB_producion
    url: <%= ENV['RSDB_PRODUCTION_REPLICA'] %>
    replica: true
