default: &default
  host: localhost
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ITMO_HSDB_development
  url: <%= ENV['DEVELOPMENT_DB'] %>

test:
  <<: *default
  database: ITMO_HSDB_test
  url: <%= ENV['TEST_DB'] %>

production:
  <<: *default
  database: ITMO_HSDB_production
  url: <%= ENV['PRODUCTION_DB'] %>
