test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  public: true

production:
  service: Disk
  root: <%= Rails.root.join("../../shared/storage") %>
  public: true
