name: CI

on:
  - push
  - pull_request

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn

      - name: Run linters
        run: |
          bundle exec rubocop --parallel
          yarn run eslint -c .eslintrc.json .

      - name: Run security checks
        run: |
          bundle exec bundler-audit --update
          bundle exec brakeman -q -w2 --skip-files app/jobs/process_csv_job.rb
  tests:
      name: Tests
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:12.7
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          ports: ["5432:5432"]
          options: >-
            --mount type=tmpfs,destination=/var/lib/postgresql/data
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        redis:
          image: redis
          ports:
            - 6379:6379
          options: --entrypoint redis-server

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Ruby and install gems
          uses: ruby/setup-ruby@v1
          with:
            bundler-cache: true

        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: 16
            cache: yarn

        - name: Install packages
          run: |
            yarn install

        - name: Setup test database
          env:
            RAILS_ENV: test
            PGHOST: localhost
            PGUSER: postgres
          run: |
            RAILS_ENV=test bin/rails db:drop
            RAILS_ENV=test bin/rails db:create
            RAILS_ENV=test bin/rails db:schema:load

        - name: Run tests
          run: bundle exec rspec; cat log/test.log
